<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="0" failed="5" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[<a href =Wed_May_12_19_56_02_IST_2021.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Wed_May_12_19_56_02_IST_2021.jpg target="_blank"><img src=Wed_May_12_19_56_02_IST_2021.jpg height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<a href =Wed_May_12_19_56_03_IST_2021.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Wed_May_12_19_56_03_IST_2021.jpg target="_blank"><img src=Wed_May_12_19_56_03_IST_2021.jpg height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<a href =Wed_May_12_19_56_03_IST_2021.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Wed_May_12_19_56_03_IST_2021.jpg target="_blank"><img src=Wed_May_12_19_56_03_IST_2021.jpg height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<a href =Wed_May_12_19_56_04_IST_2021.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Wed_May_12_19_56_04_IST_2021.jpg target="_blank"><img src=Wed_May_12_19_56_04_IST_2021.jpg height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<a href =Wed_May_12_19_56_19_IST_2021.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Wed_May_12_19_56_19_IST_2021.jpg target="_blank"><img src=Wed_May_12_19_56_19_IST_2021.jpg height=200 width=200></a>]]>
    </line>
  </reporter-output>
  <suite started-at="2021-05-12T14:26:02Z" name="DataDriven" finished-at="2021-05-12T14:26:19Z" duration-ms="17170">
    <groups>
    </groups>
    <test started-at="2021-05-12T14:26:02Z" name="Bank Manager Login Test" finished-at="2021-05-12T14:26:02Z" duration-ms="321">
      <class name="testcases.BankManagerLoginTest">
        <test-method signature="bankManagerLogin()[pri:0, instance:testcases.BankManagerLoginTest@757529a4]" started-at="2021-05-12T14:26:02Z" name="bankManagerLogin" finished-at="2021-05-12T14:26:02Z" duration-ms="132" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Bank Manager Login Failed Intentionally]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Bank Manager Login Failed Intentionally
at org.testng.Assert.fail(Assert.java:96)
at testcases.BankManagerLoginTest.bankManagerLogin(BankManagerLoginTest.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href =Wed_May_12_19_56_02_IST_2021.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Wed_May_12_19_56_02_IST_2021.jpg target="_blank"><img src=Wed_May_12_19_56_02_IST_2021.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- bankManagerLogin -->
      </class> <!-- testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test started-at="2021-05-12T14:26:03Z" name="Add Customer Test" finished-at="2021-05-12T14:26:04Z" duration-ms="1324">
      <class name="testcases.AddCustomer">
        <test-method signature="addCust(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.AddCustomer@5f78de22]" started-at="2021-05-12T14:26:03Z" name="addCust" data-provider="dp" finished-at="2021-05-12T14:26:03Z" duration-ms="391" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Himanshu]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Mahendru]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[A22111]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Add Customer Failed Intentionally]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Add Customer Failed Intentionally
at org.testng.Assert.fail(Assert.java:96)
at testcases.AddCustomer.addCust(AddCustomer.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href =Wed_May_12_19_56_03_IST_2021.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Wed_May_12_19_56_03_IST_2021.jpg target="_blank"><img src=Wed_May_12_19_56_03_IST_2021.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCust -->
        <test-method signature="addCust(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.AddCustomer@5f78de22]" started-at="2021-05-12T14:26:03Z" name="addCust" data-provider="dp" finished-at="2021-05-12T14:26:03Z" duration-ms="174" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Shivam ]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Mahendru]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[S22222]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Add Customer Failed Intentionally]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Add Customer Failed Intentionally
at org.testng.Assert.fail(Assert.java:96)
at testcases.AddCustomer.addCust(AddCustomer.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href =Wed_May_12_19_56_03_IST_2021.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Wed_May_12_19_56_03_IST_2021.jpg target="_blank"><img src=Wed_May_12_19_56_03_IST_2021.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCust -->
        <test-method signature="addCust(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.AddCustomer@5f78de22]" started-at="2021-05-12T14:26:04Z" name="addCust" data-provider="dp" finished-at="2021-05-12T14:26:04Z" duration-ms="159" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Priya]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Mahendru]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[P22111]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Add Customer Failed Intentionally]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Add Customer Failed Intentionally
at org.testng.Assert.fail(Assert.java:96)
at testcases.AddCustomer.addCust(AddCustomer.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href =Wed_May_12_19_56_04_IST_2021.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Wed_May_12_19_56_04_IST_2021.jpg target="_blank"><img src=Wed_May_12_19_56_04_IST_2021.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCust -->
      </class> <!-- testcases.AddCustomer -->
    </test> <!-- Add Customer Test -->
    <test started-at="2021-05-12T14:26:04Z" name="Open Account Test" finished-at="2021-05-12T14:26:19Z" duration-ms="15249">
      <class name="testcases.OpenAccount">
        <test-method is-config="true" signature="setup()[pri:0, instance:testcases.OpenAccount@a619c2]" started-at="2021-05-12T14:26:00Z" name="setup" finished-at="2021-05-12T14:26:02Z" duration-ms="2294" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="openAcc(java.lang.String, java.lang.String)[pri:0, instance:testcases.OpenAccount@a619c2]" started-at="2021-05-12T14:26:04Z" name="openAcc" data-provider="dp" finished-at="2021-05-12T14:26:19Z" duration-ms="15092" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Himanshu Mahendru]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Rupee]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"css selector","selector":"#userSelect"}
  (Session info: chrome=90.0.4430.93)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-ABRF4IV4', ip: '192.168.0.104', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 90.0.4430.93, chrome: {chromedriverVersion: 90.0.4430.24 (4c6d850f087da..., userDataDir: C:\Users\HP\AppData\Local\T...}, goog:chromeOptions: {debuggerAddress: localhost:62454}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: a398f9bb8ffb8e152eb86aef29e007ad
*** Element info: {Using=css selector, value=#userSelect}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#userSelect"}
  (Session info: chrome=90.0.4430.93)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-ABRF4IV4', ip: '192.168.0.104', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 90.0.4430.93, chrome: {chromedriverVersion: 90.0.4430.24 (4c6d850f087da..., userDataDir: C:\Users\HP\AppData\Local\T...}, goog:chromeOptions: {debuggerAddress: localhost:62454}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: a398f9bb8ffb8e152eb86aef29e007ad
*** Element info: {Using=css selector, value=#userSelect}
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:420)
at org.openqa.selenium.By$ByCssSelector.findElement(By.java:431)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at base.BaseTest.select(BaseTest.java:71)
at testcases.OpenAccount.openAcc(OpenAccount.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
            <line>
              <![CDATA[<a href =Wed_May_12_19_56_19_IST_2021.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Wed_May_12_19_56_19_IST_2021.jpg target="_blank"><img src=Wed_May_12_19_56_19_IST_2021.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- openAcc -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testcases.OpenAccount@a619c2]" started-at="2021-05-12T14:26:19Z" name="teardown" finished-at="2021-05-12T14:26:20Z" duration-ms="631" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testcases.OpenAccount -->
    </test> <!-- Open Account Test -->
  </suite> <!-- DataDriven -->
</testng-results>
